apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes
type: application
version: 0.16.1-bb.1
appVersion: v0.16.1
kubeVersion: ">= 1.19.0-0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
maintainers:
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
dependencies:
  - name: gluon
    version: "0.5.19"
    repository: "oci://registry1.dso.mil/bigbang"
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - External Secrets: 0.16.1
  helm.sh/images: |
    - name: external-secrets
      image: registry1.dso.mil/ironbank/opensource/external-secrets/external-secrets:v0.16.1
    - name: kubectl
      image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.32.3
    - name: kubectl-gluon
      image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.30.11  
